spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker_app
    username: postgres
    password: kjunn2000
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

